/**
 * OpenAI Embedding Pre-computation Script (Offline)
 *
 * Run ONCE with your API key set in .env:
 *   node scripts/generateEmbeddingsOpenAI.mjs
 *
 * Model: text-embedding-3-small
 *   - Dimensions: 1536 (vs 384 for MiniLM)
 *   - Multilingual: Yes (strong)
 *   - Cost: ~$0.02 per 1M tokens (12 chunks ≈ ~3000 tokens ≈ $0.00006 total)
 *
 * Output: src/data/knowledgeBaseEmbeddedOpenAI.js
 *   → same structure as knowledgeBaseEmbedded.js but with 1536-dim vectors
 */

import OpenAI from "openai";
import { readFileSync, writeFileSync } from "fs";
import { knowledgeChunks } from "../src/data/knowledgeBase.js";

// Load .env manually (no dotenv needed in Node 20+)
const envFile = readFileSync(".env", "utf-8");
const apiKey = envFile
  .split("\n")
  .find((l) => l.startsWith("VITE_OPENAI_API_KEY="))
  ?.split("=")[1]
  ?.trim();

if (!apiKey || apiKey === "your-openai-api-key-here") {
  console.error("❌ No API key found. Edit .env and set VITE_OPENAI_API_KEY=sk-...");
  process.exit(1);
}

const client = new OpenAI({ apiKey });

console.log("🔄 Using OpenAI text-embedding-3-small...\n");
console.log(`📦 Embedding ${knowledgeChunks.length} knowledge chunks...\n`);

const embeddedChunks = [];

for (const chunk of knowledgeChunks) {
  process.stdout.write(`  ⚙️  Embedding [${chunk.id}]...`);

  const response = await client.embeddings.create({
    model: "text-embedding-3-small",
    input: chunk.text,
    encoding_format: "float",
  });

  const embedding = response.data[0].embedding; // already a plain number[]

  embeddedChunks.push({ ...chunk, embedding });

  console.log(` ✓  (${embedding.length} dimensions)`);
}

console.log("\n✅ All chunks embedded!\n");

const outputContent = `/**
 * AUTO-GENERATED by scripts/generateEmbeddingsOpenAI.mjs
 * DO NOT EDIT MANUALLY.
 *
 * Model: OpenAI text-embedding-3-small
 * Dimensions: 1536
 * Chunks: ${embeddedChunks.length}
 * Generated: ${new Date().toISOString()}
 */

export const knowledgeChunksOpenAI = ${JSON.stringify(embeddedChunks, null, 2)};
`;

writeFileSync("src/data/knowledgeBaseEmbeddedOpenAI.js", outputContent, "utf-8");

console.log("💾 Saved → src/data/knowledgeBaseEmbeddedOpenAI.js");
console.log("\n🚀 Done!\n");
