/**
 * STEP 3: Pre-compute Embeddings Script
 *
 * Run this once with:
 *   node scripts/generateEmbeddings.mjs
 *
 * What it does:
 * 1. Loads each text chunk from src/data/knowledgeBase.js
 * 2. Passes each chunk through all-MiniLM-L6-v2 embedding model
 * 3. Gets back a 384-dimensional float32 vector for each chunk
 * 4. Writes the result to src/data/knowledgeBaseEmbedded.js
 *    (same structure as knowledgeBase.js, but with embedding arrays filled in)
 *
 * You only need to re-run this if you update the text chunks.
 */

import { pipeline } from "@huggingface/transformers";
import { knowledgeChunks } from "../src/data/knowledgeBase.js";
import { writeFileSync } from "fs";

console.log("🔄 Loading embedding model: paraphrase-multilingual-MiniLM-L12-v2 (~470 MB, downloads once)...");

const extractor = await pipeline(
  "feature-extraction",
  "Xenova/paraphrase-multilingual-MiniLM-L12-v2"
);

console.log("✅ Model loaded!\n");
console.log(`📦 Embedding ${knowledgeChunks.length} knowledge chunks...\n`);

const embeddedChunks = [];

for (const chunk of knowledgeChunks) {
  process.stdout.write(`  ⚙️  Embedding [${chunk.id}]...`);

  const output = await extractor(chunk.text, {
    pooling: "mean",
    normalize: true,
  });

  // Convert Float32Array to a regular JS array for JSON serialization
  const embedding = Array.from(output.data);

  embeddedChunks.push({
    ...chunk,
    embedding,
  });

  console.log(` ✓  (${embedding.length} dimensions)`);
}

console.log("\n✅ All chunks embedded!\n");

// Build the output JS file content
const outputContent = `/**
 * AUTO-GENERATED by scripts/generateEmbeddings.mjs
 * DO NOT EDIT MANUALLY.
 *
 * Re-generate by running: node scripts/generateEmbeddings.mjs
 *
 * Model: Xenova/all-MiniLM-L6-v2
 * Dimensions: 384
 * Chunks: ${embeddedChunks.length}
 * Generated: ${new Date().toISOString()}
 */

export const knowledgeChunks = ${JSON.stringify(embeddedChunks, null, 2)};
`;

writeFileSync("src/data/knowledgeBaseEmbedded.js", outputContent, "utf-8");

console.log("💾 Saved → src/data/knowledgeBaseEmbedded.js");
console.log("\n🚀 Done! Import knowledgeChunks from knowledgeBaseEmbedded.js in your app.\n");
